// <auto-generated />
using System;
using MediaRankerServer.Shared.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MediaRankerServer.Migrations
{
    [DbContext(typeof(PostgreSQLContext))]
    [Migration("20260401235402_CreateReviewDetailsView")]
    partial class CreateReviewDetailsView
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MediaRankerServer.Modules.Files.Data.Entities.FileUpload", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ActualContentType")
                        .HasColumnType("text")
                        .HasColumnName("actual_content_type");

                    b.Property<long?>("ActualFileSizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("actual_file_size_bytes");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<long?>("EntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entity_type");

                    b.Property<string>("ExpectedContentType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("expected_content_type");

                    b.Property<long>("ExpectedFileSizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("expected_file_size_bytes");

                    b.Property<string>("FileKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_key");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_name");

                    b.Property<string>("State")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Uploading")
                        .HasColumnName("state");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_file_uploads");

                    b.HasIndex("EntityType", "FileKey")
                        .IsUnique()
                        .HasDatabaseName("uq_file_uploads_entity_type_file_key");

                    b.ToTable("file_uploads", (string)null);
                });

            modelBuilder.Entity("MediaRankerServer.Modules.Media.Data.Entities.MediaEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CoverFileContentType")
                        .HasColumnType("text")
                        .HasColumnName("cover_file_content_type");

                    b.Property<string>("CoverFileKey")
                        .HasColumnType("text")
                        .HasColumnName("cover_file_key");

                    b.Property<string>("CoverFileName")
                        .HasColumnType("text")
                        .HasColumnName("cover_file_name");

                    b.Property<long?>("CoverFileSizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("cover_file_size_bytes");

                    b.Property<long?>("CoverFileUploadId")
                        .HasColumnType("bigint")
                        .HasColumnName("cover_file_upload_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<long>("MediaTypeId")
                        .HasColumnType("bigint")
                        .HasColumnName("media_type_id");

                    b.Property<DateOnly>("ReleaseDate")
                        .HasColumnType("date")
                        .HasColumnName("release_date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id")
                        .HasName("pk_media");

                    b.HasIndex("MediaTypeId")
                        .HasDatabaseName("ix_media_media_type_id");

                    b.HasIndex("ReleaseDate")
                        .HasDatabaseName("ix_media_release_date");

                    b.HasIndex("Title", "MediaTypeId", "ReleaseDate")
                        .IsUnique()
                        .HasDatabaseName("uq_media_title_type_release_date");

                    b.ToTable("media", (string)null);
                });

            modelBuilder.Entity("MediaRankerServer.Modules.Media.Data.Entities.MediaType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_media_types");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("uq_media_types_name");

                    b.ToTable("media_types", (string)null);
                });

            modelBuilder.Entity("MediaRankerServer.Modules.Reviews.Data.Entities.Review", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<long>("MediaId")
                        .HasColumnType("bigint")
                        .HasColumnName("media_id");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<short>("OverallScore")
                        .HasColumnType("smallint")
                        .HasColumnName("overall_score");

                    b.Property<string>("ReviewTitle")
                        .HasColumnType("text")
                        .HasColumnName("review_title");

                    b.Property<long>("TemplateId")
                        .HasColumnType("bigint")
                        .HasColumnName("template_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_reviews");

                    b.HasIndex("MediaId")
                        .HasDatabaseName("ix_reviews_media_id");

                    b.HasIndex("TemplateId")
                        .HasDatabaseName("ix_reviews_template_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_reviews_user");

                    b.HasIndex("UserId", "MediaId")
                        .IsUnique()
                        .HasDatabaseName("uq_reviews_user_media");

                    b.HasIndex("UserId", "TemplateId")
                        .HasDatabaseName("ix_reviews_user_template");

                    b.ToTable("reviews", null, t =>
                        {
                            t.HasCheckConstraint("ck_reviews_overall_score", "overall_score BETWEEN 1 AND 10");
                        });
                });

            modelBuilder.Entity("MediaRankerServer.Modules.Reviews.Data.Entities.ReviewField", b =>
                {
                    b.Property<long>("ReviewId")
                        .HasColumnType("bigint")
                        .HasColumnName("review_id");

                    b.Property<long>("TemplateFieldId")
                        .HasColumnType("bigint")
                        .HasColumnName("template_field_id");

                    b.Property<short>("Value")
                        .HasColumnType("smallint")
                        .HasColumnName("value");

                    b.HasKey("ReviewId", "TemplateFieldId")
                        .HasName("pk_review_fields");

                    b.HasIndex("TemplateFieldId")
                        .HasDatabaseName("ix_review_fields_field");

                    b.ToTable("review_fields", null, t =>
                        {
                            t.HasCheckConstraint("ck_review_fields_value", "value BETWEEN 1 AND 10");
                        });
                });

            modelBuilder.Entity("MediaRankerServer.Modules.Reviews.Data.Views.ReviewDetailView", b =>
                {
                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("MediaCoverFileKey")
                        .HasColumnType("text")
                        .HasColumnName("media_cover_file_key");

                    b.Property<long>("MediaId")
                        .HasColumnType("bigint")
                        .HasColumnName("media_id");

                    b.Property<string>("MediaTitle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("media_title");

                    b.Property<long>("MediaTypeId")
                        .HasColumnType("bigint")
                        .HasColumnName("media_type_id");

                    b.Property<string>("MediaTypeName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("media_type_name");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<short>("OverallScore")
                        .HasColumnType("smallint")
                        .HasColumnName("overall_score");

                    b.Property<string>("ReviewTitle")
                        .HasColumnType("text")
                        .HasColumnName("review_title");

                    b.Property<long>("TemplateId")
                        .HasColumnType("bigint")
                        .HasColumnName("template_id");

                    b.Property<string>("TemplateName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("template_name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.ToTable((string)null);

                    b.ToView("review_details", (string)null);
                });

            modelBuilder.Entity("MediaRankerServer.Modules.Templates.Data.Entities.Template", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<long>("MediaTypeId")
                        .HasColumnType("bigint")
                        .HasColumnName("media_type_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_templates");

                    b.HasIndex("Id")
                        .HasDatabaseName("uq_templates_is_system")
                        .HasFilter("id < 0");

                    b.HasIndex("MediaTypeId")
                        .HasDatabaseName("ix_templates_media_type_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_templates_user_id");

                    b.HasIndex("UserId", "Name")
                        .IsUnique()
                        .HasDatabaseName("uq_templates_user_name");

                    b.ToTable("templates", (string)null);
                });

            modelBuilder.Entity("MediaRankerServer.Modules.Templates.Data.Entities.TemplateField", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<long>("TemplateId")
                        .HasColumnType("bigint")
                        .HasColumnName("template_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id")
                        .HasName("pk_template_fields");

                    b.HasIndex("TemplateId")
                        .HasDatabaseName("ix_template_fields_template_id");

                    b.ToTable("template_fields", (string)null);
                });

            modelBuilder.Entity("MediaRankerServer.Modules.Media.Data.Entities.MediaEntity", b =>
                {
                    b.HasOne("MediaRankerServer.Modules.Media.Data.Entities.MediaType", "MediaType")
                        .WithMany()
                        .HasForeignKey("MediaTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_media_media_types_media_type_id");

                    b.Navigation("MediaType");
                });

            modelBuilder.Entity("MediaRankerServer.Modules.Reviews.Data.Entities.ReviewField", b =>
                {
                    b.HasOne("MediaRankerServer.Modules.Reviews.Data.Entities.Review", "Review")
                        .WithMany("Fields")
                        .HasForeignKey("ReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_review_fields_reviews_review_id");

                    b.Navigation("Review");
                });

            modelBuilder.Entity("MediaRankerServer.Modules.Templates.Data.Entities.TemplateField", b =>
                {
                    b.HasOne("MediaRankerServer.Modules.Templates.Data.Entities.Template", "Template")
                        .WithMany("Fields")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_template_fields_templates_template_id");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("MediaRankerServer.Modules.Reviews.Data.Entities.Review", b =>
                {
                    b.Navigation("Fields");
                });

            modelBuilder.Entity("MediaRankerServer.Modules.Templates.Data.Entities.Template", b =>
                {
                    b.Navigation("Fields");
                });
#pragma warning restore 612, 618
        }
    }
}
