// <auto-generated />
using System;
using MediaRankerServer.Shared.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MediaRankerServer.Migrations
{
    [DbContext(typeof(PostgreSQLContext))]
    [Migration("20260429200052_AddIndexesAndRemoveConstraints")]
    partial class AddIndexesAndRemoveConstraints
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MediaRankerServer.Modules.Files.Data.Entities.FileUpload", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ActualContentType")
                        .HasColumnType("text")
                        .HasColumnName("actual_content_type");

                    b.Property<long?>("ActualFileSizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("actual_file_size_bytes");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<long?>("EntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entity_type");

                    b.Property<string>("ExpectedContentType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("expected_content_type");

                    b.Property<long>("ExpectedFileSizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("expected_file_size_bytes");

                    b.Property<string>("FileKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_key");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_name");

                    b.Property<string>("State")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Uploading")
                        .HasColumnName("state");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_file_uploads");

                    b.HasIndex("EntityType", "FileKey")
                        .IsUnique()
                        .HasDatabaseName("uq_file_uploads_entity_type_file_key");

                    b.ToTable("file_uploads", (string)null);
                });

            modelBuilder.Entity("MediaRankerServer.Modules.Media.Data.Entities.ImdbImport", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int?>("EndYear")
                        .HasColumnType("integer")
                        .HasColumnName("end_year");

                    b.Property<string>("Genres")
                        .HasColumnType("text")
                        .HasColumnName("genres");

                    b.Property<bool>("IsAdult")
                        .HasColumnType("boolean")
                        .HasColumnName("is_adult");

                    b.Property<string>("OriginalTitle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("original_title");

                    b.Property<string>("PrimaryTitle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("primary_title");

                    b.Property<string>("RawLine")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("raw_line");

                    b.Property<int?>("RuntimeMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("runtime_minutes");

                    b.Property<int?>("StartYear")
                        .HasColumnType("integer")
                        .HasColumnName("start_year");

                    b.Property<string>("Tconst")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tconst");

                    b.Property<string>("TitleType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title_type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id")
                        .HasName("pk_imdb_imports");

                    b.HasIndex("Tconst")
                        .IsUnique()
                        .HasDatabaseName("uq_imdb_imports_tconst");

                    b.HasIndex("TitleType")
                        .HasDatabaseName("ix_imdb_imports_title_type");

                    b.ToTable("imdb_imports", (string)null);
                });

            modelBuilder.Entity("MediaRankerServer.Modules.Media.Data.Entities.ImdbImportEpisode", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("EpisodeNumber")
                        .HasColumnType("integer")
                        .HasColumnName("episode_number");

                    b.Property<string>("ParentTconst")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("parent_tconst");

                    b.Property<string>("RawLine")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("raw_line");

                    b.Property<int>("SeasonNumber")
                        .HasColumnType("integer")
                        .HasColumnName("season_number");

                    b.Property<string>("Tconst")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tconst");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id")
                        .HasName("pk_imdb_import_episodes");

                    b.HasIndex("ParentTconst")
                        .HasDatabaseName("ix_imdb_import_episodes_parent_tconst");

                    b.HasIndex("Tconst")
                        .IsUnique()
                        .HasDatabaseName("uq_imdb_import_episodes_tconst");

                    b.ToTable("imdb_import_episodes", (string)null);
                });

            modelBuilder.Entity("MediaRankerServer.Modules.Media.Data.Entities.MediaCollection", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CollectionType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("collection_type");

                    b.Property<long?>("CoverId")
                        .HasColumnType("bigint")
                        .HasColumnName("cover_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("ExternalId")
                        .HasColumnType("text")
                        .HasColumnName("external_id");

                    b.Property<string>("ExternalSource")
                        .HasColumnType("text")
                        .HasColumnName("external_source");

                    b.Property<long>("MediaTypeId")
                        .HasColumnType("bigint")
                        .HasColumnName("media_type_id");

                    b.Property<long?>("ParentMediaCollectionId")
                        .HasColumnType("bigint")
                        .HasColumnName("parent_media_collection_id");

                    b.Property<DateOnly?>("ReleaseDate")
                        .HasColumnType("date")
                        .HasColumnName("release_date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id")
                        .HasName("pk_media_collections");

                    b.HasIndex("CoverId")
                        .HasDatabaseName("ix_media_collections_cover_id");

                    b.HasIndex("ExternalId")
                        .HasDatabaseName("ix_media_collections_external_id");

                    b.HasIndex("MediaTypeId")
                        .HasDatabaseName("ix_media_collections_media_type_id");

                    b.HasIndex("ParentMediaCollectionId")
                        .HasDatabaseName("ix_media_collections_parent_id");

                    b.HasIndex("ExternalId", "ExternalSource")
                        .IsUnique()
                        .HasDatabaseName("uq_media_collections_external_id_source_series")
                        .HasFilter("external_id IS NOT NULL AND collection_type = 'Series'");

                    b.HasIndex("Title", "CollectionType", "MediaTypeId")
                        .IsUnique()
                        .HasDatabaseName("uq_media_collections_title_type_mediatype_root")
                        .HasFilter("parent_media_collection_id IS NULL");

                    b.HasIndex("Title", "CollectionType", "MediaTypeId", "ParentMediaCollectionId")
                        .IsUnique()
                        .HasDatabaseName("uq_media_collections_title_type_mediatype_parent")
                        .HasFilter("parent_media_collection_id IS NOT NULL");

                    b.ToTable("media_collections", (string)null);
                });

            modelBuilder.Entity("MediaRankerServer.Modules.Media.Data.Entities.MediaCover", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("FileContentType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_content_type");

                    b.Property<string>("FileKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_key");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_name");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size_bytes");

                    b.Property<long>("FileUploadId")
                        .HasColumnType("bigint")
                        .HasColumnName("file_upload_id");

                    b.Property<bool>("MarkedForCleanup")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("marked_for_cleanup");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id")
                        .HasName("pk_media_covers");

                    b.ToTable("media_covers", (string)null);
                });

            modelBuilder.Entity("MediaRankerServer.Modules.Media.Data.Entities.MediaEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("CoverId")
                        .HasColumnType("bigint")
                        .HasColumnName("cover_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("ExternalId")
                        .HasColumnType("text")
                        .HasColumnName("external_id");

                    b.Property<string>("ExternalSource")
                        .HasColumnType("text")
                        .HasColumnName("external_source");

                    b.Property<long?>("MediaCollectionId")
                        .HasColumnType("bigint")
                        .HasColumnName("media_collection_id");

                    b.Property<long>("MediaTypeId")
                        .HasColumnType("bigint")
                        .HasColumnName("media_type_id");

                    b.Property<DateOnly?>("ReleaseDate")
                        .HasColumnType("date")
                        .HasColumnName("release_date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id")
                        .HasName("pk_media");

                    b.HasIndex("CoverId")
                        .HasDatabaseName("ix_media_cover_id");

                    b.HasIndex("ExternalId")
                        .HasDatabaseName("ix_media_external_id");

                    b.HasIndex("MediaCollectionId")
                        .HasDatabaseName("ix_media_media_collection_id");

                    b.HasIndex("MediaTypeId")
                        .HasDatabaseName("ix_media_media_type_id");

                    b.HasIndex("ReleaseDate")
                        .HasDatabaseName("ix_media_release_date");

                    b.HasIndex("ExternalId", "ExternalSource")
                        .IsUnique()
                        .HasDatabaseName("uq_media_external_id_source")
                        .HasFilter("external_id IS NOT NULL");

                    b.ToTable("media", (string)null);
                });

            modelBuilder.Entity("MediaRankerServer.Modules.Media.Data.Entities.MediaType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_media_types");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("uq_media_types_name");

                    b.ToTable("media_types", (string)null);

                    b.HasData(
                        new
                        {
                            Id = -1L,
                            Name = "Video Game"
                        },
                        new
                        {
                            Id = -2L,
                            Name = "Book"
                        },
                        new
                        {
                            Id = -3L,
                            Name = "Movie"
                        },
                        new
                        {
                            Id = -4L,
                            Name = "TV Show"
                        },
                        new
                        {
                            Id = -5L,
                            Name = "Album"
                        },
                        new
                        {
                            Id = -6L,
                            Name = "Concert"
                        });
                });

            modelBuilder.Entity("MediaRankerServer.Modules.Reviews.Data.Entities.Review", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<long>("MediaId")
                        .HasColumnType("bigint")
                        .HasColumnName("media_id");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<short>("OverallScore")
                        .HasColumnType("smallint")
                        .HasColumnName("overall_score");

                    b.Property<string>("ReviewTitle")
                        .HasColumnType("text")
                        .HasColumnName("review_title");

                    b.Property<long>("TemplateId")
                        .HasColumnType("bigint")
                        .HasColumnName("template_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_reviews");

                    b.HasIndex("MediaId")
                        .HasDatabaseName("ix_reviews_media_id");

                    b.HasIndex("TemplateId")
                        .HasDatabaseName("ix_reviews_template_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_reviews_user");

                    b.HasIndex("UserId", "MediaId")
                        .IsUnique()
                        .HasDatabaseName("uq_reviews_user_media");

                    b.HasIndex("UserId", "TemplateId")
                        .HasDatabaseName("ix_reviews_user_template");

                    b.ToTable("reviews", null, t =>
                        {
                            t.HasCheckConstraint("ck_reviews_overall_score", "overall_score BETWEEN 1 AND 10");
                        });
                });

            modelBuilder.Entity("MediaRankerServer.Modules.Reviews.Data.Entities.ReviewField", b =>
                {
                    b.Property<long>("ReviewId")
                        .HasColumnType("bigint")
                        .HasColumnName("review_id");

                    b.Property<long>("TemplateFieldId")
                        .HasColumnType("bigint")
                        .HasColumnName("template_field_id");

                    b.Property<short>("Value")
                        .HasColumnType("smallint")
                        .HasColumnName("value");

                    b.HasKey("ReviewId", "TemplateFieldId")
                        .HasName("pk_review_fields");

                    b.HasIndex("TemplateFieldId")
                        .HasDatabaseName("ix_review_fields_field");

                    b.ToTable("review_fields", null, t =>
                        {
                            t.HasCheckConstraint("ck_review_fields_value", "value BETWEEN 1 AND 10");
                        });
                });

            modelBuilder.Entity("MediaRankerServer.Modules.Reviews.Data.Views.ReviewDetailView", b =>
                {
                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("MediaCoverFileKey")
                        .HasColumnType("text")
                        .HasColumnName("media_cover_file_key");

                    b.Property<long>("MediaId")
                        .HasColumnType("bigint")
                        .HasColumnName("media_id");

                    b.Property<string>("MediaTitle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("media_title");

                    b.Property<long>("MediaTypeId")
                        .HasColumnType("bigint")
                        .HasColumnName("media_type_id");

                    b.Property<string>("MediaTypeName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("media_type_name");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<short>("OverallScore")
                        .HasColumnType("smallint")
                        .HasColumnName("overall_score");

                    b.Property<string>("ReviewTitle")
                        .HasColumnType("text")
                        .HasColumnName("review_title");

                    b.Property<long>("TemplateId")
                        .HasColumnType("bigint")
                        .HasColumnName("template_id");

                    b.Property<string>("TemplateName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("template_name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.ToTable((string)null);

                    b.ToView("review_details", (string)null);
                });

            modelBuilder.Entity("MediaRankerServer.Modules.Templates.Data.Entities.Template", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<long>("MediaTypeId")
                        .HasColumnType("bigint")
                        .HasColumnName("media_type_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_templates");

                    b.HasIndex("Id")
                        .HasDatabaseName("uq_templates_is_system")
                        .HasFilter("id < 0");

                    b.HasIndex("MediaTypeId")
                        .HasDatabaseName("ix_templates_media_type_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_templates_user_id");

                    b.HasIndex("UserId", "Name")
                        .IsUnique()
                        .HasDatabaseName("uq_templates_user_name");

                    b.ToTable("templates", (string)null);

                    b.HasData(
                        new
                        {
                            Id = -1L,
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Default review template for video games.",
                            MediaTypeId = -1L,
                            Name = "Video Games",
                            UpdatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UserId = "system"
                        });
                });

            modelBuilder.Entity("MediaRankerServer.Modules.Templates.Data.Entities.TemplateField", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<long>("TemplateId")
                        .HasColumnType("bigint")
                        .HasColumnName("template_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id")
                        .HasName("pk_template_fields");

                    b.HasIndex("TemplateId")
                        .HasDatabaseName("ix_template_fields_template_id");

                    b.ToTable("template_fields", (string)null);

                    b.HasData(
                        new
                        {
                            Id = -11L,
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Gameplay",
                            Position = 0,
                            TemplateId = -1L,
                            UpdatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = -12L,
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Graphics",
                            Position = 1,
                            TemplateId = -1L,
                            UpdatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = -13L,
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Story",
                            Position = 2,
                            TemplateId = -1L,
                            UpdatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = -14L,
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Sound",
                            Position = 3,
                            TemplateId = -1L,
                            UpdatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("MediaRankerServer.Modules.Media.Data.Entities.MediaCollection", b =>
                {
                    b.HasOne("MediaRankerServer.Modules.Media.Data.Entities.MediaCover", "Cover")
                        .WithMany("MediaCollections")
                        .HasForeignKey("CoverId")
                        .HasConstraintName("fk_media_collections_media_covers_cover_id");

                    b.HasOne("MediaRankerServer.Modules.Media.Data.Entities.MediaType", "MediaType")
                        .WithMany()
                        .HasForeignKey("MediaTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_media_collections_media_types_media_type_id");

                    b.HasOne("MediaRankerServer.Modules.Media.Data.Entities.MediaCollection", "ParentMediaCollection")
                        .WithMany("ChildCollections")
                        .HasForeignKey("ParentMediaCollectionId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_media_collections_media_collections_parent_media_collection");

                    b.Navigation("Cover");

                    b.Navigation("MediaType");

                    b.Navigation("ParentMediaCollection");
                });

            modelBuilder.Entity("MediaRankerServer.Modules.Media.Data.Entities.MediaEntity", b =>
                {
                    b.HasOne("MediaRankerServer.Modules.Media.Data.Entities.MediaCover", "Cover")
                        .WithMany("MediaEntities")
                        .HasForeignKey("CoverId")
                        .HasConstraintName("fk_media_media_covers_cover_id");

                    b.HasOne("MediaRankerServer.Modules.Media.Data.Entities.MediaCollection", "MediaCollection")
                        .WithMany("MediaItems")
                        .HasForeignKey("MediaCollectionId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_media_media_collections_media_collection_id");

                    b.HasOne("MediaRankerServer.Modules.Media.Data.Entities.MediaType", "MediaType")
                        .WithMany()
                        .HasForeignKey("MediaTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_media_media_types_media_type_id");

                    b.Navigation("Cover");

                    b.Navigation("MediaCollection");

                    b.Navigation("MediaType");
                });

            modelBuilder.Entity("MediaRankerServer.Modules.Reviews.Data.Entities.ReviewField", b =>
                {
                    b.HasOne("MediaRankerServer.Modules.Reviews.Data.Entities.Review", "Review")
                        .WithMany("Fields")
                        .HasForeignKey("ReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_review_fields_reviews_review_id");

                    b.Navigation("Review");
                });

            modelBuilder.Entity("MediaRankerServer.Modules.Templates.Data.Entities.TemplateField", b =>
                {
                    b.HasOne("MediaRankerServer.Modules.Templates.Data.Entities.Template", "Template")
                        .WithMany("Fields")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_template_fields_templates_template_id");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("MediaRankerServer.Modules.Media.Data.Entities.MediaCollection", b =>
                {
                    b.Navigation("ChildCollections");

                    b.Navigation("MediaItems");
                });

            modelBuilder.Entity("MediaRankerServer.Modules.Media.Data.Entities.MediaCover", b =>
                {
                    b.Navigation("MediaCollections");

                    b.Navigation("MediaEntities");
                });

            modelBuilder.Entity("MediaRankerServer.Modules.Reviews.Data.Entities.Review", b =>
                {
                    b.Navigation("Fields");
                });

            modelBuilder.Entity("MediaRankerServer.Modules.Templates.Data.Entities.Template", b =>
                {
                    b.Navigation("Fields");
                });
#pragma warning restore 612, 618
        }
    }
}
