// <auto-generated />
using System;
using MediaRankerServer.Data.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MediaRankerServer.Migrations
{
    [DbContext(typeof(PostgreSQLContext))]
    [Migration("20260224154912_InitialSetup")]
    partial class InitialSetup
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "media_type", new[] { "album", "book", "game", "movie", "other", "tv" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MediaRankerServer.Data.Entities.Media", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<MediaType>("MediaType")
                        .HasColumnType("media_type")
                        .HasColumnName("media_type");

                    b.Property<DateOnly>("ReleaseDate")
                        .HasColumnType("date")
                        .HasColumnName("release_date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id")
                        .HasName("pk_media");

                    b.HasIndex("MediaType")
                        .HasDatabaseName("ix_media_media_type");

                    b.HasIndex("ReleaseDate")
                        .HasDatabaseName("ix_media_release_date");

                    b.HasIndex("Title", "MediaType", "ReleaseDate")
                        .IsUnique()
                        .HasDatabaseName("uq_media_title_type_release_date");

                    b.ToTable("media", (string)null);
                });

            modelBuilder.Entity("MediaRankerServer.Data.Entities.RankedMedia", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<long>("MediaId")
                        .HasColumnType("bigint")
                        .HasColumnName("media_id");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<short>("OverallScore")
                        .HasColumnType("smallint")
                        .HasColumnName("overall_score");

                    b.Property<string>("ReviewTitle")
                        .HasColumnType("text")
                        .HasColumnName("review_title");

                    b.Property<long>("TemplateId")
                        .HasColumnType("bigint")
                        .HasColumnName("template_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_ranked_media");

                    b.HasIndex("MediaId")
                        .HasDatabaseName("ix_ranked_media_media_id");

                    b.HasIndex("TemplateId")
                        .HasDatabaseName("ix_ranked_media_template_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_ranked_media_user");

                    b.HasIndex("UserId", "TemplateId")
                        .HasDatabaseName("ix_ranked_media_user_template");

                    b.HasIndex("UserId", "MediaId", "TemplateId")
                        .IsUnique()
                        .HasDatabaseName("uq_ranked_media_user_media_template");

                    b.ToTable("ranked_media", null, t =>
                        {
                            t.HasCheckConstraint("ck_ranked_media_overall_score", "overall_score BETWEEN 1 AND 10");
                        });
                });

            modelBuilder.Entity("MediaRankerServer.Data.Entities.RankedMediaScore", b =>
                {
                    b.Property<long>("RankedMediaId")
                        .HasColumnType("bigint")
                        .HasColumnName("ranked_media_id");

                    b.Property<long>("TemplateFieldId")
                        .HasColumnType("bigint")
                        .HasColumnName("template_field_id");

                    b.Property<short>("Value")
                        .HasColumnType("smallint")
                        .HasColumnName("value");

                    b.HasKey("RankedMediaId", "TemplateFieldId")
                        .HasName("pk_ranked_media_scores");

                    b.HasIndex("TemplateFieldId")
                        .HasDatabaseName("ix_ranked_media_scores_field");

                    b.ToTable("ranked_media_scores", null, t =>
                        {
                            t.HasCheckConstraint("ck_ranked_media_scores_value", "value BETWEEN 1 AND 10");
                        });
                });

            modelBuilder.Entity("MediaRankerServer.Data.Entities.Template", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_templates");

                    b.HasIndex("Name")
                        .HasDatabaseName("uq_templates_system_name")
                        .HasFilter("user_id = 'system'");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_templates_user_id");

                    b.HasIndex("UserId", "Name")
                        .IsUnique()
                        .HasDatabaseName("uq_templates_user_name");

                    b.ToTable("templates", (string)null);
                });

            modelBuilder.Entity("MediaRankerServer.Data.Entities.TemplateField", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<long>("TemplateId")
                        .HasColumnType("bigint")
                        .HasColumnName("template_id");

                    b.HasKey("Id")
                        .HasName("pk_template_fields");

                    b.HasIndex("TemplateId")
                        .HasDatabaseName("ix_template_fields_template_id");

                    b.HasIndex("TemplateId", "Name")
                        .IsUnique()
                        .HasDatabaseName("uq_template_fields_template_name");

                    b.HasIndex("TemplateId", "Position")
                        .IsUnique()
                        .HasDatabaseName("uq_template_fields_template_position");

                    b.ToTable("template_fields", (string)null);
                });

            modelBuilder.Entity("MediaRankerServer.Data.Entities.RankedMedia", b =>
                {
                    b.HasOne("MediaRankerServer.Data.Entities.Media", "Media")
                        .WithMany("RankedMedia")
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ranked_media_media_media_id");

                    b.HasOne("MediaRankerServer.Data.Entities.Template", "Template")
                        .WithMany("RankedMedia")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ranked_media_templates_template_id");

                    b.Navigation("Media");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("MediaRankerServer.Data.Entities.RankedMediaScore", b =>
                {
                    b.HasOne("MediaRankerServer.Data.Entities.RankedMedia", "RankedMedia")
                        .WithMany("Scores")
                        .HasForeignKey("RankedMediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ranked_media_scores_ranked_media_ranked_media_id");

                    b.HasOne("MediaRankerServer.Data.Entities.TemplateField", "TemplateField")
                        .WithMany("RankedMediaScores")
                        .HasForeignKey("TemplateFieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ranked_media_scores_template_fields_template_field_id");

                    b.Navigation("RankedMedia");

                    b.Navigation("TemplateField");
                });

            modelBuilder.Entity("MediaRankerServer.Data.Entities.TemplateField", b =>
                {
                    b.HasOne("MediaRankerServer.Data.Entities.Template", "Template")
                        .WithMany("Fields")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_template_fields_templates_template_id");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("MediaRankerServer.Data.Entities.Media", b =>
                {
                    b.Navigation("RankedMedia");
                });

            modelBuilder.Entity("MediaRankerServer.Data.Entities.RankedMedia", b =>
                {
                    b.Navigation("Scores");
                });

            modelBuilder.Entity("MediaRankerServer.Data.Entities.Template", b =>
                {
                    b.Navigation("Fields");

                    b.Navigation("RankedMedia");
                });

            modelBuilder.Entity("MediaRankerServer.Data.Entities.TemplateField", b =>
                {
                    b.Navigation("RankedMediaScores");
                });
#pragma warning restore 612, 618
        }
    }
}
