// <auto-generated />
using System;
using MediaRankerServer.Shared.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MediaRankerServer.Migrations
{
    [DbContext(typeof(PostgreSQLContext))]
    partial class PostgreSQLContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MediaRankerServer.Modules.Media.Entities.MediaEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<long>("MediaTypeId")
                        .HasColumnType("bigint")
                        .HasColumnName("media_type_id");

                    b.Property<DateOnly>("ReleaseDate")
                        .HasColumnType("date")
                        .HasColumnName("release_date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id")
                        .HasName("pk_media");

                    b.HasIndex("MediaTypeId")
                        .HasDatabaseName("ix_media_media_type_id");

                    b.HasIndex("ReleaseDate")
                        .HasDatabaseName("ix_media_release_date");

                    b.HasIndex("Title", "MediaTypeId", "ReleaseDate")
                        .IsUnique()
                        .HasDatabaseName("uq_media_title_type_release_date");

                    b.ToTable("media", (string)null);
                });

            modelBuilder.Entity("MediaRankerServer.Modules.Media.Entities.MediaType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_media_types");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("uq_media_types_name");

                    b.ToTable("media_types", (string)null);
                });

            modelBuilder.Entity("MediaRankerServer.Modules.Reviews.Entities.Review", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<long>("MediaId")
                        .HasColumnType("bigint")
                        .HasColumnName("media_id");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<short>("OverallScore")
                        .HasColumnType("smallint")
                        .HasColumnName("overall_score");

                    b.Property<string>("ReviewTitle")
                        .HasColumnType("text")
                        .HasColumnName("review_title");

                    b.Property<long>("TemplateId")
                        .HasColumnType("bigint")
                        .HasColumnName("template_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_reviews");

                    b.HasIndex("MediaId")
                        .HasDatabaseName("ix_reviews_media_id");

                    b.HasIndex("TemplateId")
                        .HasDatabaseName("ix_reviews_template_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_reviews_user");

                    b.HasIndex("UserId", "MediaId")
                        .IsUnique()
                        .HasDatabaseName("uq_reviews_user_media");

                    b.HasIndex("UserId", "TemplateId")
                        .HasDatabaseName("ix_reviews_user_template");

                    b.ToTable("reviews", null, t =>
                        {
                            t.HasCheckConstraint("ck_reviews_overall_score", "overall_score BETWEEN 1 AND 10");
                        });
                });

            modelBuilder.Entity("MediaRankerServer.Modules.Reviews.Entities.ReviewField", b =>
                {
                    b.Property<long>("ReviewId")
                        .HasColumnType("bigint")
                        .HasColumnName("review_id");

                    b.Property<long>("TemplateFieldId")
                        .HasColumnType("bigint")
                        .HasColumnName("template_field_id");

                    b.Property<short>("Value")
                        .HasColumnType("smallint")
                        .HasColumnName("value");

                    b.HasKey("ReviewId", "TemplateFieldId")
                        .HasName("pk_review_fields");

                    b.HasIndex("TemplateFieldId")
                        .HasDatabaseName("ix_review_fields_field");

                    b.ToTable("review_fields", null, t =>
                        {
                            t.HasCheckConstraint("ck_review_fields_value", "value BETWEEN 1 AND 10");
                        });
                });

            modelBuilder.Entity("MediaRankerServer.Modules.Templates.Entities.Template", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<long>("MediaTypeId")
                        .HasColumnType("bigint")
                        .HasColumnName("media_type_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_templates");

                    b.HasIndex("Id")
                        .HasDatabaseName("uq_templates_is_system")
                        .HasFilter("id < 0");

                    b.HasIndex("MediaTypeId")
                        .HasDatabaseName("ix_templates_media_type_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_templates_user_id");

                    b.HasIndex("UserId", "Name")
                        .IsUnique()
                        .HasDatabaseName("uq_templates_user_name");

                    b.ToTable("templates", (string)null);
                });

            modelBuilder.Entity("MediaRankerServer.Modules.Templates.Entities.TemplateField", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<long>("TemplateId")
                        .HasColumnType("bigint")
                        .HasColumnName("template_id");

                    b.HasKey("Id")
                        .HasName("pk_template_fields");

                    b.HasIndex("TemplateId")
                        .HasDatabaseName("ix_template_fields_template_id");

                    b.ToTable("template_fields", (string)null);
                });

            modelBuilder.Entity("MediaRankerServer.Modules.Media.Entities.MediaEntity", b =>
                {
                    b.HasOne("MediaRankerServer.Modules.Media.Entities.MediaType", "MediaType")
                        .WithMany()
                        .HasForeignKey("MediaTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_media_media_types_media_type_id");

                    b.Navigation("MediaType");
                });

            modelBuilder.Entity("MediaRankerServer.Modules.Reviews.Entities.Review", b =>
                {
                    b.HasOne("MediaRankerServer.Modules.Media.Entities.MediaEntity", "Media")
                        .WithMany("Reviews")
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reviews_media_media_id");

                    b.HasOne("MediaRankerServer.Modules.Templates.Entities.Template", "Template")
                        .WithMany("Reviews")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reviews_templates_template_id");

                    b.Navigation("Media");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("MediaRankerServer.Modules.Reviews.Entities.ReviewField", b =>
                {
                    b.HasOne("MediaRankerServer.Modules.Reviews.Entities.Review", "Review")
                        .WithMany("Fields")
                        .HasForeignKey("ReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_review_fields_reviews_review_id");

                    b.HasOne("MediaRankerServer.Modules.Templates.Entities.TemplateField", "TemplateField")
                        .WithMany("ReviewFields")
                        .HasForeignKey("TemplateFieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_review_fields_template_fields_template_field_id");

                    b.Navigation("Review");

                    b.Navigation("TemplateField");
                });

            modelBuilder.Entity("MediaRankerServer.Modules.Templates.Entities.Template", b =>
                {
                    b.HasOne("MediaRankerServer.Modules.Media.Entities.MediaType", "MediaType")
                        .WithMany()
                        .HasForeignKey("MediaTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_templates_media_types_media_type_id");

                    b.Navigation("MediaType");
                });

            modelBuilder.Entity("MediaRankerServer.Modules.Templates.Entities.TemplateField", b =>
                {
                    b.HasOne("MediaRankerServer.Modules.Templates.Entities.Template", "Template")
                        .WithMany("Fields")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_template_fields_templates_template_id");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("MediaRankerServer.Modules.Media.Entities.MediaEntity", b =>
                {
                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("MediaRankerServer.Modules.Reviews.Entities.Review", b =>
                {
                    b.Navigation("Fields");
                });

            modelBuilder.Entity("MediaRankerServer.Modules.Templates.Entities.Template", b =>
                {
                    b.Navigation("Fields");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("MediaRankerServer.Modules.Templates.Entities.TemplateField", b =>
                {
                    b.Navigation("ReviewFields");
                });
#pragma warning restore 612, 618
        }
    }
}
